### ISSUE TITLE
[Enhancement] 静谧四季会导致建筑工在冬季重复铲雪工作

### ISSUE THREAD

**Issue by OnlySole-IN** [Yorunina/Second-Eden#1]
下雪时，建筑工会一直铲雪。
还有能添加更多的生态群系和地貌。

**Comment by OnlySole-IN** [comment]
BetterAdvancements-NeoForge-1.20.1-0.4.2.10
geckolib-neoforge-1.20.1-4.4.7
为什么是NeoForge版本？？？

**Comment by Yorunina** [comment]
> 下雪时，建筑工会一直铲雪。 还有能添加更多的生态群系和地貌。

首先，你的git issue标题不符合规范。

这是一个已知的问题，但不会添加更多的生态群系地貌，因为这会对殖民地的选址产生巨大的影响。

其次。为什么mod是neoforge版本，是因为它不仅支持forge，也支持neoforge
