### ISSUE TITLE
[Enhancement] 锦致装饰灯笼重力燃烧会导致游戏性问题

### ISSUE THREAD

**Issue by YeYuyanMu** [Yorunina/Second-Eden#2]
锦致装饰的灯笼掉落会着火特性在建筑工建造有灯笼的建筑时，可能会掉落引起烧家

**Comment by Yorunina** [comment]
如果这个影响比较大，下版本会关闭这个特性。不过最大影响的应该是某些建筑蓝图，在制作的时候使用了灯笼，结果因为灯笼受重力影响，以及错误的建造顺序，使得整个建造流程不可用
